### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by seularts** [Vire7777/TG2-Legacy#1]
Hi there,

I've been testing this mod for the past few days and I ran into 2 serious issues:

1. My main character marries a wife, gets her pregnant and when I let her in the house alone and put her to study, the game just gives me all the tiles and 1 million gold. At first I thought it was the game's fault so I made a clean install and added the mod and have the same issue. Might be just a glitch in the code somewhere.

2. The civil tax is very confusing. My town (London) has the sale tax to 0% so I do not know if that is the same as the civil tax and then the civil tax seems to be activated per business building I own. For example: I build my first building in year 1 and kept paying the taxes and in year 4 I build my second building and in year five I got 2 messages to pay my civil taxes that were probably 30-40 seconds apart from each other. I thought that once the first message expired the tax will be paid globally for both buildings but then 30-40 seconds later my second business was seized. My problem here is that I do not know where to look and see how much civil tax I need to prepare in advance so I know how much money I have to save up. I like the tax system but it's very counterproductive when it comes to managing your own finances.

**Comment by Vire7777** [comment]
Hello

So about the first one, it s an error. We just use it for our test. I
suppose one of us commited it by mistake. Sorry for that

About the second, i m actually developping it and i put the first version
yesterday or two days ago.

The civil tax is a totally different sysyem from the other taxes. It s a
tax you have to pay each turn. Normally they tell you how much you have to
pay when you pay them or don t pay them.

Nethertheless, What you tell me is strange. I ll have a look

**Comment by seularts** [comment]
Thank you for the reply,

Here is the attached savegame of my playthough. H2 is right after I start building the Fishery (2nd business), and H3 is when I get 2 Civil Tax alerts at short intervals one after the other. It would be useful if there would be an information tab in the Finances GUI that calculates the total amount of taxes so I can get a better understanding of how much I need to have before the next year so I don't constantly rush to sell my wares in those 6 hours if I am short on the required cash.

https://file.re/2020/12/15/savegames/

**Comment by Vire7777** [comment]
I already corrected the train thing (was just a small mistake commit)

For the taxes, here is the formula tax = sumBuildingPrices * (titleLevel *
2 + 20) / 100
But yes, maybe a little tip somewhere could be nice, that s right
Also we could even make a mayor decision to put the taxes higher or lower
like the market taxes

**Comment by seularts** [comment]
If I may be so bold to recommend an alternative prototype tax system that could improve your own:

You could make a safety cushion of a maximum of 4 turns to delay paying your taxes, but the catch is that each turn the there is an interest rate of 15%/10%/5% (depending on your titles), meaning that they act a bit like loans (maybe make a similar button like the guild loans to check how much tax debt you have at the town hall with the option to pay it manually before the 4 turns expire and if not paid manually then the sum should be subtracted automatically after those 4 years if the player has enough gold). The more you wait the more you have to pay (an alert will inform the player each turn of the debt's interest rate). And if after 4 years the player did not pay, he loses all his estates (perhaps putting the business up for sale at the town hall rather than razing them to the ground so the player will have to pay the steep price to buy them back to save the time to rebuild and retrain the staff), or maybe a less harsh option would be to through some family members in jail while only some businesses will be taken away instead of all. I think this gives the player more versatility and time to invest in upgrades early on rather than constantly concern he will run out of cash and has to prioritize to expand cautiously slower. Slowing the player also gives a rather unfair advantage to the AI dynasties as they always knows how much to invest and how much to save for taxes by default.

Thank you for your time and help. Really appreciate it and I'm super happy with how this project is turning out! Will keep you guys updated if I find any funky bugs :)

**Comment by Vire7777** [comment]
you know, i would love to make something like this but... the guild 2
system is so buggy that it s difficult to make something working
sadly

So i have to find alternative all the time
I pass more time finding alternatives than the contrary

but i ll try to see how to make this
1) i ll update the tax messages for you to know how much you need to pay
2) i ll try looking at your system

**Comment by seularts** [comment]
You are the best ^__^

**Comment by Vire7777** [comment]
So i did a few changes

1) Now you have in the city hall the formula to calculate your taxes when
you ask to see the laws

2) When you click on your guy, you have now an option to see the amount of
civil tax you ll have to pay

3) When you are sentenced to death, you really get arrested by the guards
(if they find you) and you go to be executed (it didn t work but now yes)

4) All your buiding can be seized EXCEPT your actual house (so if you are
living in a mansion, it stays yours but you can be punished to death anyway)

That s it for the moment

**Comment by Vire7777** [comment]
By the way i won t change the actual tax system as you said

Why ?
Because now that you can see how much you ll have to pay, you ll have to be
careful about it
For sure if you forget, you ll still have 6h to find the money (i could
make it 12 if you think that s not enough) but i think 6h is good before
you are seized
Also this system is not so expensive at first but for rich people, it ll
really make them going slower.
That s why this tax system is on

At first steps, it should n t make you problem if you are careful

**Comment by seularts** [comment]
No, no the 6h time period is enough with all the changes done. I will check out the modifications soon. Damn, those tax people really don't play around when they want their taxes: the money or your life :P

Would there be a way (if my character would be arrested) to ransom him out of jail, or does he go to the execution directly?

**Comment by Vire7777** [comment]
For the moment he goes to execution directly
But if you prefer, i can make it two ways
Like...

Step 1 => pay his tax
Step 2 => 6h : not enough money => seize buildings
Step 3 => direct : not enough money with the seize => Go to jail for...
Step 4 => 12h : still not enough money => is killed

==> your character can be setenced to death after 18h without paying

And be careful, because it starts with your first character, but then the
next day, you ll have to pay again your taxes (hopefully, after the seize
and everything, it ll be so much less but your title can make them high
still)
And so if you don t pay the next day (24h later), your next char ll go the
same process

**Comment by seularts** [comment]
Yeah, this option with the steps to be jailed and then later executed is good. Just make sure the character is let go when the taxes are paid :D

It would also help if I could pay the taxes manually so I can get my character out of jail faster instead of waiting for the time period to expire.

I just tested a small play through but something weird just happened. I had 2 businesses, the first was seized and then the next day I waited without paying taxes I was sentenced to death directly while I still had my second business getting the message: was sentenced to death because there were no money or property to seize.

[usersave_0004.zip](https://github.com/Vire7777/TG2-Legacy/files/5698069/usersave_0004.zip)

**Comment by seularts** [comment]
By the way, I am impressed with how fast and efficient you made these changes. As I said, I only proposed the prototype, you have the technical know-how on what is possible or not to implement withing the scripting environment. I have no doubts that the game was left in a somehwat poor coding state by the developers.

**Comment by seularts** [comment]
Also, if you can create custom buttons for checking the Civil Tax, I make graphic design for a living, so I can design you the visual buttons to associate them in the game so it can add more flair instead of recycling the default graphics.

**Comment by Vire7777** [comment]
Contact me maybe on discord : vivi#2288
would be easier to exchange

i put a new version with small bug correction and multiplayer also (bc it
was not multi before)
I also tried with different buildings and all of them were seized
So...

Did you started a new game ?
because the corrections only work with new games (sadly)

**Comment by seularts** [comment]
Ah I see now. Yeah, it was an older savegame, you are right! Sure. I'll add you there now :)

**Comment by Vire7777** [comment]
Perfect, waiting for you :)

**Comment by seularts** [comment]
Hmmm, seems I can't find you there. Could you try to add me: Errare-humanum-est#5623

**Comment by Vire7777** [comment]
close
